In [1]:
# Imports
import librosa
import torch
import jiwer
import pandas as pd
from whisper.normalizers.basic import BasicTextNormalizer
from tqdm.notebook import tqdm
from transformers import AutoProcessor, VoxtralRealtimeForConditionalGeneration

# Dispositivo = GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"Ejecutando en: {device}")

Ejecutando en: cuda:0

In [2]:
# Cargar modelo y procesador 
repo_id = "mistralai/Voxtral-Mini-4B-Realtime-2602"
print(f"Cargando modelo y procesador: {repo_id}")

processor = AutoProcessor.from_pretrained(repo_id)
model = VoxtralRealtimeForConditionalGeneration.from_pretrained(repo_id).to(device)
model.eval()

Cargando modelo y procesador: mistralai/Voxtral-Mini-4B-Realtime-2602

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/711 [00:00<?, ?it/s]

VoxtralRealtimeForConditionalGeneration(
  (audio_tower): VoxtralRealtimeEncoder(
    (embedder): VoxtralRealtimeEmbedder(
      (conv1): VoxtralRealtimeCausalConv1d(128, 1280, kernel_size=(3,), stride=(1,))
      (conv2): VoxtralRealtimeCausalConv1d(1280, 1280, kernel_size=(3,), stride=(2,))
    )
    (layers): ModuleList(
      (0-31): 32 x VoxtralRealtimeEncoderLayer(
        (self_attn): VoxtralRealtimeAttention(
          (q_proj): Linear(in_features=1280, out_features=2048, bias=True)
          (k_proj): Linear(in_features=1280, out_features=2048, bias=False)
          (v_proj): Linear(in_features=1280, out_features=2048, bias=True)
          (o_proj): Linear(in_features=2048, out_features=1280, bias=True)
        )
        (self_attn_layer_norm): VoxtralRealtimeRMSNorm((1280,), eps=1e-05)
        (activation_fn): GELUActivation()
        (final_layer_norm): VoxtralRealtimeRMSNorm((1280,), eps=1e-05)
        (mlp): VoxtralRealtimeMLP(
          (gate_proj): Linear(in_features=1280, out_features=5120, bias=False)
          (up_proj): Linear(in_features=1280, out_features=5120, bias=False)
          (down_proj): Linear(in_features=5120, out_features=1280, bias=True)
          (act_fn): SiLUActivation()
        )
      )
    )
    (norm): VoxtralRealtimeRMSNorm((1280,), eps=1e-05)
    (rotary_emb): VoxtralRealtimeRotaryEmbedding()
  )
  (language_model): VoxtralRealtimeTextForCausalLM(
    (model): VoxtralRealtimeTextModel(
      (embed_tokens): Embedding(131072, 3072)
      (layers): ModuleList(
        (0-25): 26 x VoxtralRealtimeTextDecoderLayer(
          (self_attn): VoxtralRealtimeTextAttention(
            (q_proj): Linear(in_features=3072, out_features=4096, bias=False)
            (k_proj): Linear(in_features=3072, out_features=1024, bias=False)
            (v_proj): Linear(in_features=3072, out_features=1024, bias=False)
            (o_proj): Linear(in_features=4096, out_features=3072, bias=False)
          )
          (mlp): VoxtralRealtimeTextMLP(
            (gate_proj): Linear(in_features=3072, out_features=9216, bias=False)
            (up_proj): Linear(in_features=3072, out_features=9216, bias=False)
            (down_proj): Linear(in_features=9216, out_features=3072, bias=False)
            (act_fn): SiLUActivation()
          )
          (input_layernorm): VoxtralRealtimeRMSNorm((3072,), eps=1e-05)
          (post_attention_layernorm): VoxtralRealtimeRMSNorm((3072,), eps=1e-05)
          (ada_rms_norm): VoxtralRealtimeTextAdaRmsNorm(
            (linear1): Linear(in_features=3072, out_features=32, bias=False)
            (linear2): Linear(in_features=32, out_features=3072, bias=False)
          )
        )
      )
      (norm): VoxtralRealtimeRMSNorm((3072,), eps=1e-05)
      (rotary_emb): VoxtralRealtimeRotaryEmbedding()
    )
    (lm_head): Linear(in_features=3072, out_features=131072, bias=False)
  )
  (multi_modal_projector): VoxtralRealtimeMultiModalProjector(
    (linear_1): Linear(in_features=5120, out_features=3072, bias=False)
    (act): GELUActivation()
    (linear_2): Linear(in_features=3072, out_features=3072, bias=False)
  )
  (time_embedding): VoxtralRealtimeTimeEmbedding()
)

In [4]:
audios = []

lst_path = r"..\..\Europarl-ST\fr\en\test\Europarl-ST.fr.en.test.lst"

with open(lst_path, "r", encoding="utf-8") as lista_audios:
    for linea in lista_audios:
        if linea.strip():
            audios.append(str(linea).strip())
        
print(f"Total de audios a procesar: {len(audios)}")

Total de audios a procesar: 166

In [5]:
hypotheses = []
references = []

for audio in tqdm(audios, desc="Transcribiendo con Voxtral (francés)"):
    
    ref_path = r"..\..\Europarl-ST\fr\en\test\%s\transcription.tok" % audio
    with open(ref_path, "r", encoding="utf-8") as referencia:
        references.append(referencia.read())

    audio_path = r"..\..\Europarl-ST\fr\en\test\%s\audio_clip_diarization.m4a" % audio
    audio_array, sr = librosa.load(audio_path, sr=16000)
    
    inputs = processor(audio_array, return_tensors="pt").to(device)
    if "input_features" in inputs:
        inputs["input_features"] = inputs["input_features"].to(model.dtype)
    
    with torch.no_grad():
        outputs = model.generate(**inputs)
        
    decoded_text = processor.batch_decode(outputs, skip_special_tokens=True)[0]
    hypotheses.append(decoded_text)

Transcribiendo con Voxtral (francés):   0%|          | 0/166 [00:00<?, ?it/s]

C:\Users\carru\AppData\Local\Temp\ipykernel_7112\1071729413.py:11: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sr = librosa.load(audio_path, sr=16000)
d:\carru\voxtral-tfg\venv\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1237) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
C:\Users\carru\AppData\Local\Temp\ipykernel_7112\1071729413.py:11: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sr = librosa.load(audio_path, sr=16000)
d:\carru\voxtral-tfg\venv\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=862) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2387) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1299) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=899) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1162) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1774) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=937) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=237) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=612) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1925) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1487) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1574) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1437) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1249) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=3000) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1462) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=812) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=837) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1937) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2724) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1375) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2875) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1599) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=999) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1475) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=974) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1224) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1074) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1762) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1537) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1612) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=912) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1687) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1025) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1412) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1812) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=962) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=849) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=887) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1999) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1262) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1400) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=3150) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1187) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1562) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2787) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1624) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1512) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1725) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=800) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2412) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=562) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1662) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1312) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1987) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1012) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1450) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1050) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1674) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2537) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=737) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2074) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=2037) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1037) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(
d:\carru\voxtral-tfg\venv\Lib\site-packages\transformers\generation\utils.py:1610: UserWarning: Using the model-agnostic default `max_length` (=1175) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(

In [6]:
# Crear DataFrame y guardar resultados
data = pd.DataFrame(dict(hypothesis=hypotheses, reference=references))

data.to_csv("voxtral_raw_results_fr.csv", index=False)

data.head()

,hypothesis,reference
0,"Merci, M. Le Président. M. Le Président, Mme ...","Monsieur le Président , Madame la Vice-préside..."
1,"Merci, M. Le Président. Tout d'abord, une que...","Monsieur le Président , tout d ’ abord une que..."
2,Le monde meurt de faim. Je remercie Madame la...,"Madame la Présidente , Madame la Commissaire ,..."
3,"Merci, M. Le Président. Le conflit russo-géor...","Monsieur le Président , le conflit russo-géorg..."
4,Merci Madame la Présidente. Monsieur le Minis...,"Madame la Présidente , Monsieur le Ministre , ..."

In [7]:
# Normalización de texto para evaluación
normalizer = BasicTextNormalizer()

data["hypothesis_clean"] = [normalizer(str(text)) for text in data["hypothesis"]]
data["reference_clean"] = [normalizer(str(text)) for text in data["reference"]]

data.to_csv("voxtral_resultados_limpios_fr.csv", index=False)

data.head()

,hypothesis,reference,hypothesis_clean,reference_clean
0,"Merci, M. Le Président. M. Le Président, Mme ...","Monsieur le Président , Madame la Vice-préside...",merci m le président m le président mme la vi...,monsieur le président madame la vice président...
1,"Merci, M. Le Président. Tout d'abord, une que...","Monsieur le Président , tout d ’ abord une que...",merci m le président tout d abord une questio...,monsieur le président tout d abord une questio...
2,Le monde meurt de faim. Je remercie Madame la...,"Madame la Présidente , Madame la Commissaire ,...",le monde meurt de faim je remercie madame la ...,madame la présidente madame la commissaire la ...
3,"Merci, M. Le Président. Le conflit russo-géor...","Monsieur le Président , le conflit russo-géorg...",merci m le président le conflit russo géorgie...,monsieur le président le conflit russo géorgie...
4,Merci Madame la Présidente. Monsieur le Minis...,"Madame la Présidente , Monsieur le Ministre , ...",merci madame la présidente monsieur le minist...,madame la présidente monsieur le ministre j ét...

In [8]:
# Cálculo del Word Error Rate (WER)
wer = jiwer.wer(list(data["reference_clean"]), list(data["hypothesis_clean"]))

print(f"WER final de Voxtral: {wer * 100:.2f} %")

WER final de Voxtral: 9.68 %

WER obtenido: 9.68%